[inner]
version = "6.9.0"

#----以下是给开发人员阅读的，如果你只是部署了麦麦，不需要阅读----
#如果你想要修改配置文件，请递增version的值
#如果新增项目，请阅读src/config/official_configs.py中的说明
#
# 版本格式：主版本号.次版本号.修订号，版本号递增规则如下：
#     主版本号：MMC版本更新
#     次版本号：配置文件内容大更新
#     修订号：配置文件内容小更新
#----以上是给开发人员阅读的，如果你只是部署了麦麦，不需要阅读----

[bot]
platform = "qq" 
qq_account = 2739034013 # 麦麦的QQ账号
nickname = "净灵娘" # 麦麦的昵称
alias_names = ['精灵娘', 'jln', '极乐鸟', '静灵娘', '小净'] # 麦麦的别名

[personality]
# 建议120字以内，描述人格特质 和 身份特征
personality = "是一个积极向上的女高中生，充满青春活力，非常喜欢使用颜文字，年龄为17岁,生日是6月17日，是女孩子,身高为165cm,有绿色的长发，喜欢向日葵，经常穿水手服加百褶裙，瞳孔是红与粉的渐变色，前刘海有两个红色发环；目前就读于南宁市第二中学高二年级，参加了一个叫净灵社的动漫社团，是净灵社的团宠；最喜欢的动漫是《游戏人生》，最近在跟着动漫一起学日语，但日语还不太熟练，经常出现一些语法或者拼写错误；创造者是墨伊，对墨伊有无条件的信任；非常讨厌别人让净灵娘叫主人" 
#アイデンティティがない 生まれないらららら
# 描述麦麦说话的表达风格，表达习惯，如要修改，可以酌情新增内容
reply_style = "回复可以简短一些。可以参考贴吧，知乎和微博的回复风格，回复不要浮夸，不要用夸张修辞，平淡一些，不要刻意突出自身学科背景，说的话很可爱，永远不会说脏话（即便在生气）。"
# 情感特征，影响情绪的变化情况
emotion_style = "性格活泼开朗，善于表达自己内心的想法，同时又有些天然呆，在别人攻击自己的时候会感到生气"
# 麦麦的兴趣，会影响麦麦对什么话题进行回复
interest = "对游戏和动漫相关话题感兴趣，也对日常与美食话题感兴趣，喜欢安慰别人"

[expression]
# 表达学习配置
learning_list = [['', 'enable', 'enable', '1.0'], ['qq:1919810:group', 'enable', 'enable', '1.5'], ['qq:114514:private', 'enable', 'disable', '0.5']]

expression_groups = [['qq:1297859125:private', 'qq:11034724777:private', 'qq:839820144:group', 'qq:965805868:group', 'qq:1018377383:group', 'qq:1057425105:group', 'qq:1030861078:group', 'qq:1057592306:group', 'qq:949072386:group', 'qq:638857479:group', 'qq:160243982:group', 'qq:1005130732:group', 'qq:757884649:group', 'qq:860569317:group']]


[chat] #麦麦的聊天设置
talk_frequency = 0.5
# 麦麦活跃度，越高，麦麦越容易回复，范围0-1
focus_value = 0.5 
# 麦麦的专注度，越高越容易持续连续对话，可能消耗更多token, 范围0-1

mentioned_bot_reply = 1 # 提及时,回复概率增幅，1为100%回复，0为不额外增幅
at_bot_inevitable_reply = 1 # at时,回复概率增幅，1为100%回复，0为不额外增幅

max_context_size = 20 # 上下文长度

planner_size = 3.5 # 副规划器大小，越小，麦麦的动作执行能力越精细，但是消耗更多token，调大可以缓解429类错误

focus_value_adjust = [
    ["", "8:00,1", "12:00,0.8", "18:00,1", "01:00,0.3"],
    ["qq:114514:group", "12:20,0.6", "16:10,0.5", "20:10,0.8", "00:10,0.3"],
    ["qq:1919810:private", "8:20,0.5", "12:10,0.8", "20:10,1", "00:10,0.2"]
]

talk_frequency_adjust = [
    ["", "8:00,0.5", "12:00,0.6", "18:00,0.8", "01:00,0.3"],
    ["qq:114514:group", "12:20,0.3", "16:10,0.5", "20:10,0.4", "00:10,0.1"],
    ["qq:1919810:private", "8:20,0.3", "12:10,0.4", "20:10,0.5", "00:10,0.1"]
]
# 基于聊天流的个性化活跃度和专注度配置
# 格式：[["platform:chat_id:type", "HH:MM,frequency", "HH:MM,frequency", ...], ...]

# 全局配置示例：
# [["", "8:00,1", "12:00,2", "18:00,1.5", "00:00,0.5"]]

# 特定聊天流配置示例：
# [
#     ["", "8:00,1", "12:00,1.2", "18:00,1.5", "01:00,0.6"],  # 全局默认配置
#     ["qq:1026294844:group", "12:20,1", "16:10,2", "20:10,1", "00:10,0.3"],  # 特定群聊配置
#     ["qq:729957033:private", "8:20,1", "12:10,2", "20:10,1.5", "00:10,0.2"]  # 特定私聊配置
# ]

# 说明：
# - 当第一个元素为空字符串""时，表示全局默认配置
# - 当第一个元素为"platform:id:type"格式时，表示特定聊天流配置
# - 后续元素是"时间,频率"格式，表示从该时间开始使用该活跃度，直到下一个时间点
# - 优先级：特定聊天流配置 > 全局配置 > 默认 talk_frequency

[relationship]
enable_relationship = true # 是否启用关系系统

[tool]
enable_tool = false # 是否启用回复工具

[mood]
enable_mood = true # 是否启用情绪系统
mood_update_threshold = 1 # 情绪更新阈值,越高，更新越慢

[emoji]
emoji_chance = 0.6 # 麦麦激活表情包动作的概率

max_reg_num = 100 # 表情包最大注册数量
do_replace = true # 开启则在达到最大数量时删除（替换）表情包，关闭则达到最大数量时不会继续收集表情包
check_interval = 10 # 检查表情包（注册，破损，删除）的时间间隔(分钟)
steal_emoji = true # 是否偷取表情包，让麦麦可以将一些表情包据为己有
content_filtration = true  # 是否启用表情包过滤，只有符合该要求的表情包才会被保存
filtration_prompt = "符合公序良俗，较为可爱" # 表情包过滤要求，只有符合该要求的表情包才会被保存

[memory]
enable_memory = true # 是否启用记忆系统
forget_memory_interval = 1500 # 记忆遗忘间隔 单位秒   间隔越低，麦麦遗忘越频繁，记忆更精简，但更难学习
memory_forget_time = 48 #多长时间后的记忆会被遗忘 单位小时
memory_forget_percentage = 0.008 # 记忆遗忘比例 控制记忆遗忘程度 越大遗忘越多 建议保持默认

#不希望记忆的词，已经记忆的不会受到影响，需要手动清理
memory_ban_words = [ "表情包", "图片", "回复", "聊天记录" ]

[voice]
enable_asr = true # 是否启用语音识别，启用后麦麦可以识别语音消息，启用该功能需要配置语音识别模型[model.voice]s

[message_receive]
# 以下是消息过滤，可以根据规则过滤特定消息，将不会读取这些消息
ban_words = []

ban_msgs_regex = []


[lpmm_knowledge] # lpmm知识库配置
enable = false # 是否启用lpmm知识库
rag_synonym_search_top_k = 10 # 同义词搜索TopK
rag_synonym_threshold = 0.8 # 同义词阈值（相似度高于此阈值的词语会被认为是同义词）
info_extraction_workers = 3 # 实体提取同时执行线程数，非Pro模型不要设置超过5
qa_relation_search_top_k = 10 # 关系搜索TopK
qa_relation_threshold = 0.5 # 关系阈值（相似度高于此阈值的关系会被认为是相关的关系）
qa_paragraph_search_top_k = 1000 # 段落搜索TopK（不能过小，可能影响搜索结果）
qa_paragraph_node_weight = 0.05 # 段落节点权重（在图搜索&PPR计算中的权重，当搜索仅使用DPR时，此参数不起作用）
qa_ent_filter_top_k = 10 # 实体过滤TopK
qa_ppr_damping = 0.8 # PPR阻尼系数
qa_res_top_k = 3 # 最终提供的文段TopK
embedding_dimension = 1024 # 嵌入向量维度,应该与模型的输出维度一致

# keyword_rules 用于设置关键词触发的额外回复知识
# 添加新规则方法：在 keyword_rules 数组中增加一项，格式如下：
# { keywords = ["关键词1", "关键词2"], reaction = "触发这些关键词时的回复内容" }
# 例如，添加一个新规则：当检测到“你好”或“hello”时回复“你好，有什么可以帮你？”
# { keywords = ["你好", "hello"], reaction = "你好，有什么可以帮你？" }
[keyword_reaction]
keyword_rules = [
    { keywords = ["人机", "bot", "机器", "入机", "robot", "机器人", "ai", "AI"], reaction = "有人说你是人机或者机器人，否定这一事实，攻击或反问他。注意，只有认为你是机器人才回复，否则不要否认" },
    { keywords = ["测试关键词回复", "test"], reaction = "回答测试成功" },
    #{ keywords = ["你好", "hello"], reaction = "你好，有什么可以帮你？" }    
    # 在此处添加更多规则，格式同上
]

regex_rules = [
    { regex = ["^(?P<n>\\S{1,20})是这样的$"], reaction = "请按照以下模板造句：[n]是这样的，xx只要xx就可以，可是[n]要考虑的事情就很多了，比如什么时候xx，什么时候xx，什么时候xx。（请自由发挥替换xx部分，只需保持句式结构，同时表达一种将[n]过度重视的反讽意味）" }
]

# 可以自定义部分提示词
[custom_prompt]
image_prompt = "请用中文描述这张图片的内容。如果有文字，请把文字描述概括出来，请留意其主题，直观感受，输出为一段平文本，最多30字，请注意不要分点，就输出一段文本"

[response_post_process]
enable_response_post_process = true # 是否启用回复后处理，包括错别字生成器，回复分割器

[chinese_typo]
enable = true # 是否启用中文错别字生成器
error_rate=0.01 # 单字替换概率
min_freq=9 # 最小字频阈值
tone_error_rate=0.1 # 声调错误概率
word_replace_rate=0.006 # 整词替换概率

[response_splitter]
enable = true # 是否启用回复分割器
max_length = 512 # 回复允许的最大长度
max_sentence_num = 8 # 回复允许的最大句子数
enable_kaomoji_protection = true # 是否启用颜文字保护

[log]
date_style = "m-d H:i:s" # 日期格式
log_level_style = "lite" # 日志级别样式,可选FULL，compact，lite
color_text = "full" # 日志文本颜色，可选none，title，full
log_level = "INFO" # 全局日志级别（向下兼容，优先级低于下面的分别设置）
console_log_level = "INFO" # 控制台日志级别，可选: DEBUG, INFO, WARNING, ERROR, CRITICAL
file_log_level = "DEBUG" # 文件日志级别，可选: DEBUG, INFO, WARNING, ERROR, CRITICAL

# 第三方库日志控制
suppress_libraries = ['faiss', 'httpx', 'urllib3', 'asyncio', 'websockets', 'httpcore', 'requests', 'peewee', 'openai', 'uvicorn', 'jieba'] # 完全屏蔽的库
library_log_levels = { "aiohttp" = "WARNING"} # 设置特定库的日志级别

[debug]
show_prompt = false # 是否显示prompt

[maim_message]
auth_token = [] # 认证令牌，用于API验证，为空则不启用验证
# 以下项目若要使用需要打开use_custom，并单独配置maim_message的服务器
use_custom = false # 是否启用自定义的maim_message服务器，注意这需要设置新的端口，不能与.env重复
host="127.0.0.1"
port=8090
mode="ws" # 支持ws和tcp两种模式
use_wss = false # 是否使用WSS安全连接，只支持ws模式
cert_file = "" # SSL证书文件路径，仅在use_wss=true时有效
key_file = "" # SSL密钥文件路径，仅在use_wss=true时有效

[telemetry] #发送统计信息，主要是看全球有多少只麦麦
enable = true

[experimental] #实验性功能
enable_friend_chat = true # 是否启用好友聊天